# Generated by Django 5.1 on 2025-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'No binario'), ('S', 'Sin determinar')], max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('comuna_residencia', models.PositiveIntegerField()),
            ],
        ),
    ]
