# Generated by Django 5.1 on 2025-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'No binario'), ('S', 'Sin determinar')], max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('comuna_residencia', models.PositiveIntegerField(choices=[(1, 'Comuna 1'), (2, 'Comuna 2'), (3, 'Comuna 3'), (4, 'Comuna 4'), (5, 'Comuna 5'), (6, 'Comuna 6'), (7, 'Comuna 7'), (8, 'Comuna 8'), (9, 'Comuna 9'), (10, 'Comuna 10'), (11, 'Comuna 11'), (12, 'Comuna 12'), (13, 'Comuna 13'), (14, 'Comuna 14'), (15, 'Comuna 15')])),
            ],
        ),
    ]
