# Generated by Django 5.1 on 2025-05-26 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('amenazas', 'Amenazas'), ('lesiones dolosas', 'Lesiones dolosas'), ('otros delitos contra las personas', 'Otros delitos contra las personas'), ('otros delitos contra la integridad sexual', 'Otros delitos contra la integridad sexual'), ('otros delitos contra la libertad', 'Otros delitos contra la libertad'), ('abusos sexuales con acceso carnal', 'Abusos sexuales con acceso carnal'), ('homicidios dolosos', 'Homicidios dolosos'), ('homicidios dolosos en grado de tentativa', 'Homicidios dolosos en grado de tentativa'), ('abuso sexual simple', 'Abuso sexual simple'), ('abuso sexual agravado', 'Abuso sexual agravado')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=50, unique=True)),
                ('fecha_ocurrencia', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comisaria', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('delito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncia', to='denuncia.delito')),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncia', to='victima.victima')),
            ],
        ),
    ]
